### ISSUE TITLE
Byteball 64 Bit Crashes on Intel NUC under Windows 10 Pro 64 Bit

### ISSUE THREAD

**Issue by ghost** [byteball/obyte-gui-wallet#195]
Hi,

The Byteball version I'm using (1.9.1) crashes if I use the 64 Bit version on my Intel NUC NUCC6CAYH. Mikhael1 on Bitcointalk.org wrote that this is because the NUC has a Celeron processor that is missing certain processor instructions.

This has been the case for at least a few versions back. I haven't tried the newer version yet but I guess this is the same as the bug was never addressed.

BTW, the 32 bit version runs fine.

Maybe this is just a matter of setting the right compiler settings so that the Celeron processor is also supported?

**Comment by tonyofbyteball** [comment]
Since 4.0.0 we use Electron, feel free to reopen if the issue persists.
