### ISSUE TITLE
updated dependencies, for angular its bugged > ~1.5

### ISSUE THREAD

**Issue by cruzlauroiii** [byteball/obyte-gui-wallet#199]
PR: https://github.com/byteball/byteball/pull/198
Status

READY

What does this PR accomplish?
updated dependencies, for angular its bugged > ~1.5
so angular and angular-touch in bower is limited to ~1.5

Where should the reviewer start?
execute command:
yarn upd

How should this be manually tested?
yarn upd
yarn sqfix #fix sqlite folder dependency name
yarn  grunt
yarn nw

Any background context you want to provide?
should have latest dependency

Questions:
why?
uses latest dependency; but still dependent to bower

**Comment by tonyofbyteball** [comment]
we upgraded to more recent angular
