### ISSUE TITLE
Failed to pay: Too many authors. Consider splitting the payment into two units.

### ISSUE THREAD

**Issue by pxrunes** [byteball/obyte-gui-wallet#200]
Hi,

i'm managing mutiple blackbyte transactions from many users. Now my headlesswallet encountered the above error message. This messages appears for all amounts bigger as around 100kBytes.

How can i prevent his message? It worked just fine before and the error comes unexpected.

**Comment by tonyofbyteball** [comment]
I guess you have to split the payment in two or more.

Blackbytes exist in coins of a few standard denominations, and each coin is transferred individually.  And there is a limit of 128 messages per unit.

Since there is no solution for this problem in the core, you have to analyze the unspent outputs you have, how many of them you would need for your payment, and if this number exceeds 128, do a smaller payment and then try paying the rest.

**Comment by pxrunes** [comment]
how can i "choose" which to send? I guess the wallet would do this by itself. Is it maybe so that the wallet does not choose very "smart"? Because when i transfer 5 GBB to my wallet and want to send it back it doesnt work (with the above error) but it should be possible theoretically. Maybe the wallet always wants to send first or last arrived coins or something like that?

Would it be possible to have the wallet choose always the best fitting combination of coins?

By the way i tryed just what you said, sending a few smaller amounts but it didnt helped with the overall problem.

Also maybe its related to an other problem i have, i have 2 pending blackbyte transactions, each 5 GBB. Its pending for a few days now. Could that be related to the issue?

**Comment by tonyofbyteball** [comment]
The algorithm that chooses outputs to spend might not be smart enough, see https://github.com/byteball/byteballcore/blob/master/indivisible_asset.js#L405 (I think you already saw it).

You can also run into "too many inputs" issue.  To reduce its likelihood, consider using only amounts which are multiples of the highest denomination coin (100 KBB).

> Also maybe its related to an other problem i have, i have 2 pending blackbyte transactions, each 5 GBB. Its pending for a few days now. Could that be related to the issue?

Do you find their units on the explorer?  Is it on GUI or headless wallet?

**Comment by pxrunes** [comment]
I am using the headless wallet.
I already completly wiped it because i couldnt get rid of the error. As an interesting fun fact: i also got the "Too many authors" error when withdrawing the normal bytes. I thought this error was only possible with blackbytes. Anyway i managed to get most of the normal bytes out in small chuncks.

to the always pending problem: i know think that i maybe was able to make a double spend somehow and this was the resulting problem. I might be able to dig out the units from the database later this day.
