### ISSUE TITLE
Put a warning in documentation about free apple developer accounts making the app expire

### ISSUE THREAD

**Issue by thedavidmeister** [byteball/obyte-gui-wallet#205]
I'm not an iOS developer, I basically just have an account so I can get apps to build on my phone like ByteBall. I imagine there are others like me who can bumble through the compiling process but don't know the nuances of the apple developer program.

Got stung by the app "crashing" repeatedly on iPhone, took several days to get help in the helpdesk chat and most people just said "get an Android" and "iPhone is not really supported" - so it seems like not many people are aware of the situation and so cannot give good advice when it comes up.

In reality, the iPhone app build simply expires if you are a using a free developer account and you need to go through the process of rebuilding the app in Xcode when you want to use it. Basically this is only useful if you want to use it for an extra device as multisig on an account, I can't imagine anyone being happy repeatedly rebuilding an app that they want to use often.

I think this situation should come with some warnings/explanations in the README so that people know what to expect.

<img width="948" alt="byteball_building-for-ios_md_at_master_ _byteball_byteball" src="https://user-images.githubusercontent.com/629710/29259316-31e14132-8105-11e7-96ec-ec4b9b907b17.png">

**Comment by tonyofbyteball** [comment]
That's correct, but not relevant any more since we have an app in the app store.
