### ISSUE TITLE
Changing Currency

### ISSUE THREAD

**Issue by sltwtr-apps** [byteball/obyte-gui-wallet#217]
It's not clear how I would clone this repo to use my own currency.   Could someone point me in the right direction?  It is all in 1 config file?

**Comment by tonyofbyteball** [comment]
If you want to issue your own currency on the platform, see https://github.com/byteball/byteballcore/wiki/Issuing-assets-on-Byteball

**Comment by wizzard0** [comment]
Somehow related, how to give assets a readable name?

**Comment by tonyofbyteball** [comment]
two options:
https://obyte.app/
https://medium.com/obyte/whats-next-for-obyte-decentralized-token-registry-b87d455deeea
