### ISSUE TITLE
GlobalChat contact stealing focus on Android 1.10.1

### ISSUE THREAD

**Issue by TheButterZone** [byteball/obyte-gui-wallet#234]
How do I make it freaking stop?

**Comment by TheButterZone** [comment]
Anything else you're doing in the app, the app switches to GlobalChat by itself. https://superuser.com/questions/18383/preventing-applications-from-stealing-focus

**Comment by tonyofbyteball** [comment]
latest version?
Open e.g. Send tab, does it switch then?

**Comment by TheButterZone** [comment]
Is https://github.com/byteball/byteball/releases 1.10.1 not the latest version?

Yes, it switches then. Anything.

**Comment by tonyofbyteball** [comment]
i can't reproduce it on my android, please give detailed instructions

**Comment by TheButterZone** [comment]
Launch app, login with password, immediately put tablet on table & walk away, come back to find GlobalChat has stolen focus.

**Comment by tonyofbyteball** [comment]
This is normal if you leave it on the Home tab and any message arrives, the app automatically opens that chat.  I asked you above if this happens when in the **Send** (or any other) tab.

**Comment by TheButterZone** [comment]
And I answered 

> Yes, it switches then. 

If that wasn't clear enough:

Launch app, login with password, switch to Send (or any other) tab, immediately put tablet on table & walk away, come back to find GlobalChat has stolen focus.

**Comment by tonyofbyteball** [comment]
That's what I couldn't reproduce.  The app stays on Send tab while the badge on the chat tab grows as new messages arrive.
