### ISSUE TITLE
long SQL query, sync takes forever

### ISSUE THREAD

**Issue by Quark-Fusion** [byteball/obyte-gui-wallet#236]
long query took 6594ms:
SELECT dependencies.unit, unhandled_joints.unit AS unit_for_json, 
				SUM(CASE WHEN units.unit IS NULL THEN 1 ELSE 0 END) AS count_missing_parents 
			FROM dependencies 
			JOIN unhandled_joints ON dependencies.unit=unhandled_joints.unit 
			LEFT JOIN units ON dependencies.depends_on_unit=units.unit 
			 
			GROUP BY dependencies.unit 
			HAVING count_missing_parents=0 
			ORDER BY NULL,

**Comment by tonyofbyteball** [comment]
how often does this long query appear?

**Comment by iensu69** [comment]
see #238 
compared a freshly installed full node vs the one with a slow sync.
the freshly installed one does around 3 "long query" per second, while the slowly syncing one repeatedly does none for  around 30 seconds.

noted this:
```
long query took 34477ms:
SELECT DISTINCT unit, content_hash FROM units JOIN messages USING(unit) 
			WHERE main_chain_index<=? AND main_chain_index>=? AND sequence='final-bad', 1159625,1159624
load avg: 0, 0, 0
```
and many of these:
```
long query took 530ms:
SELECT dependencies.unit, unhandled_joints.unit AS unit_for_json, 
				SUM(CASE WHEN units.unit IS NULL THEN 1 ELSE 0 END) AS count_missing_parents 
			FROM dependencies 
			JOIN unhandled_joints ON dependencies.unit=unhandled_joints.unit 
			LEFT JOIN units ON dependencies.depends_on_unit=units.unit 
			 
			GROUP BY dependencies.unit 
			HAVING count_missing_parents=0 
			ORDER BY NULL, 
load avg: 0, 0, 0
```

**Comment by Quark-Fusion** [comment]
new version filtered log:
[ppgbkonninhcodjcnbpghnagfadnfjck-1509031035036.log](https://github.com/byteball/byteball/files/1418970/ppgbkonninhcodjcnbpghnagfadnfjck-1509031035036.log)

**Comment by iensu69** [comment]
checking the console on v1.11.2 I don't get shown those long queries anymore.
sync still slower than real time.
still getting shown the ...["dependencies"],["saved_private"],["dependencies"],["saved_private"],["dependencies"],... a lot

**Comment by iensu69** [comment]
my issue was solved by one of the last releases. probably can be closed

**Comment by tonyofbyteball** [comment]
Fixed in recent versions.
