### ISSUE TITLE
Uncaught exception: The wallet  v.1.10.1crush with this msg:

### ISSUE THREAD

**Issue by sestoculo** [byteball/obyte-gui-wallet#245]
The wallet  v.1.10.1crush with this msg:

Uncaught exception: Error: Error: SQLITE_ERROR: too many SQL variables SELECT unit_authors.unit, unit_authors.address, 100 AS earned_headers_commission_share FROM unit_authors LEFT JOIN earned_headers_commission_recipients USING(unit) WHERE unit_authors.unit IN(?) AND earned_headers_commission_recipients.unit IS NULL UNION ALL SELECT unit, address, earned_headers_commission_share FROM earned_headers_commission_recipients WHERE unit

**Comment by stevesbrain** [comment]
Good thing we're up to 1.11.2 now :)

**Comment by tonyofbyteball** [comment]
Fixed in more recent versions.
