### ISSUE TITLE
Uncaught exception: Error: removing stable witnessed unit on latest wallet

### ISSUE THREAD

**Issue by umatej** [byteball/obyte-gui-wallet#248]
Hi.

I installed latest release of wallet and it was working ok for few hours. Then, i guess wallet (v1.11.2) closed itself and after launching it i got this error.  I wasnt home.. wallet was slowly syncing...

**Uncaught exception: Error: removing stable witnessed unit 3xLncQ......= from main chain**

**Comment by KingCaper** [comment]
Same here.

`stack Error: removing stable witnessed unit 3xLncQ1OM2aRMdHyMxNuNZ22Arto2p8h8Xxpnjq6C5Q= from main chain
    at Error (native)
    at /home/user/byteball-linux64/node_modules/byteballcore/main_chain.js:80:12
    at Statement.<anonymous> (/home/user/byteball-linux64/node_modules/byteballcore/sqlite_pool.js:113:6)`

**Comment by burtw** [comment]
I am also getting this issue.  I have heard there is a fix in the works.  Is there an estimate as to when the fix will be released?

**Comment by heyjoey** [comment]
Same error on Mac version.  Uncaught exception: Error: removing stable witnessed unit

**Comment by Hennig1977** [comment]
my client also crashes on startup. (Windows)
Uncaught exception: Error: removing stable witnessed unit 
3xLncQ......................rto2p8h8Xxpnjq6C5Q= from main chain

**Comment by Sorrow2** [comment]
new version 1.12.3
got error when syncing at 5 november

>  Uncaught exception: Error: removing stable witnessed unit 3xLncQ1OM2aRMdHyMxNuNZ22Arto2p8h8Xxpnjq6C5Q= from main chain

**Comment by umatej** [comment]
Also here, new version 1.12.3

It stopped syncing at 5 november 2:22 PM, then after restarting the app/wallet it started to sync again. Looks like it is going to sync to the end.

**Comment by berbant** [comment]
v.1.11.4, W10_64. There is a change :( 
"Uncaught exception: Error: removing stable units 5H/U5u9QPjg51guRqhGu9zJXl2/4niwvw1snGCbP7sk=, RK........" at 11/5, 4.22PM

**Comment by Sorrow2** [comment]
I have upgraded to 11.4. Now when i run it from previous error, i am getting

> Uncaught exception: Error: no unindexed MC units?

**Comment by Sorrow2** [comment]
I have upgraded to 11.5. Now i am getting

>  Uncaught exception: Error: removing stable units 5H/U5u9QPjg51guRqhGu9zJXl2/4niwvw1snGCbP7sk=, RKCuNcUcP6yEk9XL5uMbDFDgD/j6dj2tRVfUBHPaqGg=, A0R5Ehnyp8al+3943lash+3Fn0qQI7BJlKi1BD6YqyI=, 8u9oLSQ4jxrOvPV6dN6V9ZQvYHEKfv5QKwU8lZDWr94=, pKRkzEjViFG4WhWAPZYy7zHuIC97YO/q5PUdM6sZzoQ=, B3XbCYH9LHFK/EWu8m8Jm3sCB93JD7u69BJwKYI0SxA=, 8z7Pyp4PX7wl9eAv+vQSKC2JLsTRFLWAztog2jmSJ4A=, 5t1UrYCxmklGMbNmK0VqwAhWrXEgJMOFrJE5WjT2vMw=, +kxhyDcjC1zSo/kXIFTAQEykB6Aar/7D6kCpZ05Or8A=, aYY39lFF2qnwdf4XOl27bHfwIDM9cXONCwVrEO9nakY=, qwqXNJUFg8FJ3SPCuLYFCNVjUtLSGx95aSkDnwfnmzc=, YLhyPOnQ7TVrTS5rSnLsqe8mTNMs9PBRUqisZRfi334=, IT4s2YWqQamr04F6Wc99fSEdH9QMYnFLnM0oMafiVZ0=, qhGct5elR3zSUlGsHWnKwF0Y4VbsWbiJbnjldwe+7nI=, bwlEnGHQ8JZdNw7JZTf5e4j4wPSpLpPSjgUp/DLUJbw=, e9aVyRvms/fgpl0MwhgED+kCShMgofRHo6QX4Rx1844=, 6/4MXEO64airdWhUlbLBLAYcEVJIA+F0qlIVzudViwI=, Z9Yb5eyUbKhx2g+5UsqGnZ/fOUcdi9A4nu6A4YjcRqk=, Frjju5dqloncYYh0UugQKG2k01cNhtQktrwO0vuhlos=, wzPC7RBOxIuAwiNXG8Bcfb6gmTeM8BaXJ7at6DhM274=, rPHTNbfGrlluwO3AoPR+hayqjDk4WQQCOWhVgotSLgo=, 0Pfv5Vk+NjuzupkUkolvs/GuX4bQEO3ATcSa4ZbuWP0=, HIwmAnW3Q7DvbpNB3saAgN4I/2Z3jEPaMtPx7nMNdKA=, Agln+swc2qBlY/nFpyEl+kzTAwiGlpQgsiprFfQz/ds=, SXcElHulWunrrO8tzsjvphQ/hahJgAuiWnYrNB5zKMA=, 2vtVdlzv0x30IX1/y/GmOKJEK8zMPkZ0K+sEsJ9BdnU=, BK+q4pcVcl1dTSUdIjonPkq4DrqdaKzvBvdfxsuT9t4=, 3Pu5T+S7Ys6HFYQugSfJoiVH6ZarOHya6jXZqmj1ERA=, fTNIM1T/CMqMvc+vK4Mas0RyAc3kquj6tzu0VqFLWs8=, YKoNZd1P9mYuSVqVCHN5k9X3M1ghB4hmRvfee9rzJI0=, YHDkHUvhu7qH4rqLvU9vzae1r/l0vzE+xykNAici8Xw=, rlM0uJNQfSdPvaoSxoU8Ol7umfqEDg98Vj+WjYV0rr0=, t74KGf7OggC4ZT1VyzAA/yWtt/BoJEyIzndqBm9tVMM=, mkN8EgZnINBgyx1bL9Yi0bUwjjZhSJQMYmRj6p+M+T8=, lb3aQsKllLKwCxxbPJkXGtLE5ihQQ4lDzpUh+V5z0bA=, d9oF2FR0e0uQxzQ+RrHm2Z8CPoJHEvUlKcQKYpjRuAI=, m758SH893qVh8+ai6do/uYZ1lBuIzP8f0M7YODnPH1I=, QwNI1KpcXMzMuOtP9CsLZ+BUQkmJxUZ0yvr+NcEiryI=, g7v4hI7IJCUNGXh97QI5ADr8zFi2cQ0KkKqsZZ5cDEA=, HAZxMxMU60DXagfT4luK4CZjTL6zuuQo9ZMhIZDAWy0=, edwD05PwsrzDy4wOuB3B7dEORE9xLCjnjTegky1fKdg=, 8+RwdQmg992f+s9sPWP6uZnREAnF/gSLk0Mep519E48=, ZQaszxC2q5w6W6yYQrL93GvpHF99pOEuPcuF1z/vd3k=, t1h9Um0iDXvg4e4qsftUboo1xu4yMMoPbVisvaPf3Zc=, DqhkEXze3LqaVD6+Job5necN+wfiOsKPQePjnL1vq1g=, 5t3whxb4ScoOjMgxjC1ZUQKPkuBT5VH+fcrArHzGt9g=, 7RoDw6xURXd9+7XZcWKadikp3P9O8TuR0Az7HepwXEU=, AoLrUfJZTty0vjVWXEzqy/OhgjOF25LYMJfNluK/Y/A=, O5E6qA9QmApKofkxndrzBEH+4vETNaEFObgz1GK2yCU=, d3Cb8Yj8pMtb/ecDWjCPMsdYCRt9nebOwCTJl1MLABQ=, +JLeGf+oAJrJkRqNpANeZbVHEedhsXgamlZUibJSISY=, mnlgJeJuoVSL/jdAf5SpxSEXw5B8Afbca0/LKFrA0Rk=, SjohNY0ByXQ8dYbeSfRw25nAo1P11XT/ycZalaq4DFk=, OhSADhnlvfAkYvqTBvzaxwfjUNm3W0pTHTMj3ACf77s=, m0Rx82JuquhSUsG6PBQIQ/tNbnsie7IByA0N/SDG5m4=, 4WhIIq7Wb5NhccgDVDzYBK39GSFTQc9KRxHt+go8pTY=, DA+1mmUehktFG358WkDHRfw6FpzFHSz0N0ytFlgud3I=, 36FRK2HF3e08kB+oPVSKMhJivQjwiL8lMkBAl6jiiww=, HN/FUCToYUPqYibfh2M6RTL4jWoRSq3lRZHvIom7YS4=, 5wS0Mx71M454c18YJpAA3t2IINoFim08bcKdf2qZDs4=, cQiC6N1dBItVkFF+CO8YKxr3rr4fdsuIzNRSmJhPgnU=, sx1WUGLxyQbYihFPLR3DVZfR7zEmwkAreDT90yQATcI=, 49HJMSak38tXYNhAufWyac1H2mvRHon9+fGmylj2O14=, xyzxFbwcHeDROTWGHKMViVHkK5kgqV355Sjji/tBIGY=, gc8iAz6DKzVbmGmcSAWPuAgPTUXaXPjR3UzcgCGj8L0=, EjPB1+ch/6OlzzmU+7PQeEMdL8XWnTaH5lzKN8/wCt4=, jsR5vYr+nxCEuUMLpt8ICtopqAz8GyJer8Fi+GpA+rQ=, M70hMthp54JuMz+PeQMIeGURe9aAFvLzEmkqXsocoH0=, 7zKc/UON0nN/WdSsXBpZNZ3XBfi5CupMhmHwdoezXL4=, BmYyWHvP7JT/0iHVfxSD4yoInqVq1CM0geRIjOaA5w0=, t4RTX1rKVkW1LHVYbRsDeyfpVx5nvNQ98UCQJd3gJos=, RadT19/XwU4KIoPYwpbIkMS74Kw03lG1UylYBfPDKEg=, A3nRqgo5vbMPobUY1ok8lDwlPILu3UixZXVRayvNVWI=, DBE+idmVZ5H59XOFDEvXbdkafOxyCnJX//ZytR/cvdg=, LYhMvvdhUy7m/Y3gxC07wyWiit+f9VaXuhqJiniuPsU=, npw9kXnDZgpiChA49d/llI6A0EidLks2BNy+icPR0R0=, wVLV95W/UAvBEcp0TY9cZIQDqTYl4rR8+KrB9qYZIqQ=, 5zi3v7qac3PqVi5Ahb8G/qMcbKin6QKCZC5USOeFXY0=, fnoEhLyvCsUIH7k0wHo6TBAU1wgrgwESqHUtTbbfK9I=, HTSpWTBTonpVxYD8v0gFuMPVYzByY7dvd/dS3WqSHQM=, JCe+KgL+m4O7UKELSoOL0CQws9Op17u3elmxlFFcawk=, e5A+jMxyxneIDlf2QNia5j6FA5aHVjT6HH0ocLFWek4=, vgGWe3KO6GsxwZ56s5E3qflHM5gVYjfaZaoGztMEXzs=, Ga9NyJJ5HnAfps/UlZKSqcJVP3S8OmZP2z+1s1+yupE=, 1o7i9yXrmIoB7VkdTeD7NWl76COn0DVnPFhgAKmQ2o0=, DkLDcOVdKvbQm+WcnsqXrGLv3Q5FcEciVOw8In5kwSo=, bwnwJta7iXRYIT410D7mBmCYYLEgZN9f6kQD3K7yDLo=, NVcgr+whIlEYZYL9P47NofpmcNMJ6vS2npJ7JoHptIg=, L5E/kA+sDZW2kEz1K7H1HAkmfjcZiXhto7gy6+SZ4xk=, UygkYva63kC5dbhNVuuvfisdciFgzq3WXAISWJuUbNM=, zUeSLqXtkMs4QBcrvtMS88Rh+aHrinLsBlWzLdOOMwk=, mnmXYEHCbY2atE9Jy38IYX+75C/X/adSlG2urI8PLZs=, JFYH/sGMbRoDZvZUn85Q3l6A61BGOdstcMbi1xznaXk=, TzJB6Q8mkYHWuzJx1EJ7Ok/t6BotgLiY/nGc7UFF2tU=, lrMj1q2knHL601/PWEZQNmDLWNFVnv5xUBMI8wyev3g=, LAg1a5UZSUlYZeWi6EZv5cDcSp0zTv/IYIp560o3/vI=, gIenT7WXKcbK4az2Hjofvl485H8H8n0EaJNnQBbkiDE=, bOmf4hNVjb6KiqpMzPMAgxwrzj4oqRb1XHAg1KeNQk4=, ASFUyO5mK0VXnCYGTX1fvcOM8VY14iT7L9f5FnRW4Zs=, BErBucXZ1/WzS0LrsG0zb69vfPRwipmohz5ymZTlE9Y=, 9SNfgtYbDr+2bWO0bwGdGspTFNGXUGzTEWhmxXsGNUU=, /+h32c2p88+XkwRWDRMftRb3SHoVeT8v4rMmcCdn49w=, mZ6gy7iuy+tqev5n/+hLpFN6qgQ80gi4VYUb9h3sR14=, goPdzDHyDN7rJplsFos+5wjyfgb+JCBhHEb3McN7lvE=, QYR5v5vit7ORy4YukUD19aPZM9uo+/1TnvCSliR/07A=, ZEIsZSsvcmSik5K3S1rKaBvMb/T4uclWjRfLU56p7LI=, sH8JcoBwAR0XGTDWeL9mzSzRfWx1du4m9Pe8F7GHQP8=, TAZglHr5ohu9Ypw+vMiXxCEdjBLyoff6GqNp2iBxIWM=, 1N1o8U/g77xWTGcMHuDjaY+CpPydEK9qhDfFL5be+1w=, GWXKP9wkPEWbJ0H4rYX3XFSV5KwGg1GxL2GDXFfpPe8=, OO5I4qEMfJBRVUaHiiwPfIJvQXQQXWg758pxicxJxXc=, jQlr7SFCd8/03yJEwXOkJsln1xd4CyUnJi9bz3Qp+t8=, 7Gma+MeBPdPPz7wW49K8ckPg6+npirMJFnXMJ6pMKP0=, djIuwGBaRugPnAZqs9yyvMFpXckwHRUd3jC3Q6qDr/4=, Yqvba3s1jir+x7VH1Ce3L4Sqmv0EdcZNAp1HY22i2tk=, +deRQFLMjGzwAMkE3iQfdxMLkulXs0HXoiGk8Xx6gT0=, 3hbjmDr1giRn7C6ukmGUOXBwUu777LaVnLJmU/pjP6o=, NNMHx2yoHaqv3/iU+l3wnv/T6udFSJmKps8CdFGDAeI=, 1UDpHEdPBYkkkLHQtlpgmjhmjyU3jPoX83sFsLTpHFU=, aJ6f9JKdWljRiu6kDa3rn94nl5yJ78ZRnUrG06Be+lg=, K2+9FnpvzkRlESvSwQ5NEZ5VuXICwxsX7uE29PFMORI=, sU47fZz23R9iZloJP5xXkyTqe4Q8JG1o3aOFvnLrQ0s=, WPn/laKTPyF0H0JcaQFibIYsQHjCpiKWVOKTluhnLDU=, VJO3xpO1WQJlPSYyRrof/nHvbtxyBipkwSucChSW9io=, +aTLDnoMTK6ZSkyfUvPghiL2eehN6CS/W9OB6u3ftJ8=, mC+NE/WznifTCn5hFwgqq9/UYO2KUOx2NqGaWVF0QIc=, FnRtL127TmXNLCYL9Zpz+fsN/wpLmZzzdKXfrpkju84=, TJyoZVXIJSUHXGG20J0quXzmsfSDWcSNzIXByiTbfzg=, O1W2qdpc5DChOnNTPqllVvohHkksOKplcvUAYyw0hi0=, kHU6lMpxvAkfiE7Q1DTH8ClQqq9lwkQ96PP8mMlJM1M=, P19Co/LJe4zqSEAEc4Cd93E4VBMsn1sp4hITN8VCfu0=, 7KKn1SeL6NaypUxTGe1DDQzl8BII6O9wZe3TM4tHFYo=, sbiSeV8Tc9SDSuwNb5gGGA0e6imvAMKhwXZqyf6pGLE=, 39/qFKwfQP8GH6kxeTkAvy8UJx4fXKBVN4b4DA66j78=, o3OzLRoKqXnos8sWBPs22J5hV+FNPJrX7ovXTq6gVM0=, Z1BiTjszNexksTcgalVA4aKmKEPEPTb1plMpOoXe8iQ=, eE+KyaCfdLGl2rq7R+3+kAB7vko/Mni4UPeSa2IkpMg=, B/ZSZHdFJmljy0mUzn2hAK1Gix5sgU71bXOI6DScHTE=, 2OWy50Skk3XrrJEQgu40tcwk3MaSmb0SH2Qjw2v8768=, r0+9gEiE3AsGA+RxP0jHEDF3aTPGO93Fez9T+fxpZd0=, atArpBFrsoR+DNXZLiFgoOhTkIA8u9X1Hb/Piyz3ofk=, xcLmudqtu0iFg59NYgK5kWhIu4R60zMZKC6ZlRFzAQk=, h4dfaKVZie02TBKN9JeZyUbiaRb07qNRQIeX046BCR4=, CkD2Byoqd448xKCm71nxVjWtfOZ+FMpAvbNvqbmT7qY=, kqCeLJAeN9rXwYTnLpsKPje/P6BO6n5KLR1l93FGAUU=, ck4fjhrhfvWwc0oz660fIhp4piaH9KnGN9Xd28yX4V4=, GCVnoZdxxcNWYQ1CUNgkWxLEPbZCaVUPFENXgBgGGQM=, wc6RQJd87bhGLDmBkDqlH70vV96xFcq22B1sqXA0/Nc=, QGBXjTpnRMcaGbB5uZs6O4IUDqPw8Lge+tW/g9CiRJc=, 7fG/WClsQgyB/XlzRPdG+W2tNDlhAf3tr4cVqlt7vI0=, 6zwddWj4vJrMKapy76opaXmmDdWt3386iOZWspaWf+8=, kTE6RkYaTgCLhJs+eGx4yy3/f7F8XZxfWI7Uf2GaXyc=, +zHoErnuf4Fs6gQwRJPdFpCdVVxkLmuxw25ArhOfzTI=, UoAlaaF8JfX+UUIOOq9AChjSuz95o/NpQswrjoKbprA=, MTulCX+cc7sEbcKYTDz8h8emfQibcG9wz5aeNf/YA+M=, J2bVLm6bbf/1fIiiwaUGfkpzs8hbJY/wJJqA8n82H88=, 4XyDN9Xh9JFaAVrir1TN4g0rAsgqNfWvDGqamvVQQcw=, MTxHhcZDr3GHry4+0sf3NHImIlyDf8Ku8xULRh7tpwQ=, oiWZlX+EK0OvyugCSUoXhfJJC7AT49jg4gK9bK7TvMM=, C/+ukIkrYKDUzMmUdoBsLBvsWZXKVvV0TdqilNBd4DY=, U/kzlKH+8aCkWhdkCVWgzNq2nBtcCzP047NuIAA+9rI=, khwhq8DS7wwRqslfgZpkqxBCzH0XpBqC+Scleza7odg=, BRHoOux2EGw2joyhzMX9H0PDJ4YHe2gAsYCOgU97xZE=, t6lCt2JVxoKMfpy67nTIC8SoRoWF3zDuHJNTq5AyNGs=, iJOzGGg6YWbuqSbUGrKqMdQE2wdd3FhFwLR81p2AYUY=, 06e71Vm12jyZc6RyqOidjUV5UxdIZYaBXmzvjGjDvyc=, 6qadCtvn42/Nxfu9iQhCNnXaXpMx7aRMGeUp55FBoP4=, FfKwTfx/RQV3djtkYO0oLEcK6Opa1P1jliqJzz63uS4=, khOq4RYqXvfY+JNJ7B+xZzjaF55u84fkryrdN578/bI=, 2el1xWWXvmApq08kWq8aupgfh5dA1/T71Yp0inmzSAA=, 5vTcAgWrOio6oQiGP3qOAEynRO1D0aS47Qkn2oQ83f8=, aVwkiv0tnulRksXNV1tLRsXCMIz4NtkpGZYPz9tfUUA=, gFMvVPrf22yQEgdyB7jcB/B+pdeZskGA9CYYQaoFDeg=, /H2w7vy/X95lqWxjt0L2tJ8AnyOBw9Q5f+YZPSdU5to=, /wxFWFJvwQDLBIppiEQrmjbmtFxlnRt19E01T1na/BY=, KBcdw0+eV7OMoZUXj+Dq68z8oBIt8sMx35EjqgFZg1c=, 0ByL2zyvHqE9GvA8k6fdCHqk4rt2la9ttne5qlmm4bw=, 1Nx1TBcGl1bsLgZ0uMroBCBAFxHtUuurvxgM1Y+vZdU=, USWESSmaUBaDuyRBmcvPkDPYBvGngr/jvvbGip8rTs0=, bNCJSE8nFJtj0xhPB9UjCNeIaTQNzPM3ODcXkGoOCtg=, zNiOKI+YTRzG7b16SRQCBsMKeil6ImeXD+rUndhb1d4=, AOkcANqHJmIhagkYKYHziHEzhTTzB/jGvgGhm2BDhYw=, EKUKS1N/QtWKTyB5mP1MECwSe2gJT3XzlAxF24rwHvY=, IllIEQThFbmdx8r7DPPrwZhD3Q3VLHeh39qrfYi29Co=, BAQtIaOnB24DkzsI4KgIAb8ZuzOVLyme+N6OiHtE+G8=, 06Wh2TcqEUWTKiwpDOssxRX9RLGPIxq511SB+6Gi0C8=, N/mz/UbmSZGw1L4W9ZQia5KI5eIplDE1xnAZcDiSxwI=, dck2Pdd36Bd54RWUJ4VvyV9XNZYT6mKX5iF5xqQBMlI=, tCRhqxv1HXogAp6ALWjFRPAySiyyFTgh6d4Bd1XobQ4=, Ti5sdCaPXrf8XaHmWuLF7I6jSRBaE0T4v7HkzRQVnjI=, G+7r1C6xMv9ReKwW5ojvx9PxpRZiu8oOBQQ4vPrUI+0=, ALbTMeSmiTxOb6X8rexAnHolhFNAFPkOQOlC7nl47NE=, 9CN6HB5E2AiCfQ53q7dLTIuez0VZAJ0Fz4wzO9vkPZw=, RweURDJ4Pb5/uQW7iDytupCwHbZDyQzO+1EC4mxmE18=, Zg/rkRy0wqRWSfnzG6U2onx0gfSlqLVT63f7em91UeU=, BHHYAOS6qnPVk9o3u11d6n6KWcO71Dh9LO+YohlfLeE=, 89SaseleTtBWewgRok9EiQ2ASpI5zNfPZT1WVqUu5MM=, qu+nlSbq/kaT1KeQOP9wnwVAT3cU7/QQcfNW3+CoJOA=, X/HdPu7BGES0ZOFBpHOqOsyzffOYhzK/8RlvrVUI53Y=, WLcZF3lsgmSMyKXMgtCHDxAr9WbAPj/yoBNcuZ0l2XY=, fiYqnec3VgX0Cu5n9oc73W8ecTGimQcf85/+NOhStu8=, 9EqLDsnqvZDRvp7A/UunyN2ycvCqmbeLJ/WtA9byDog=, yNBb9xUpA/tbHMnXFYJu8nZwLAtSlafhy6gzCpY4xFc=, fpGIaQKmv71V8XJgKCnMa5F/YwGXld4XILkdpZAEJwQ=, v1EX1nUbtUxsOT5y1x8K67Oyff3eCRMP1bKgi7LYgGA=, 0AJQ3mEgfHlp96HuwU8NRmjlfdmKNRjTL10hr+3WpwM=, eX1ZthUNIEH3e78Y/eJKTz5irQ0froPf/urp7n98WhM=, 1ojz38WepfJ5Y3FRODX8eT2IKpu1Gv8Lpl0cKTgY8bs=, RV9s/wzvNAmiAcwWOxY9RgRDGgywo2I0mANbflwYjBA=, gNZND2V5itp9LHCbwaHsljmPjUsoJ5u73OKsmPJpQOo=, daKV8dwpsqV8zspeH4UwQbNGpL7VA4VJ1tJ8bh7i234=, rnnsEa1YBe2vDNdVVDZCjY1s/MeYbtbTthbjbwBTEd4=, dFABVCjaeMemS6noZve0s29QUYTn+PklmURXoB1Apcg=, 8WoN2GfqyHR2nyprr3rhcNRMedYceX8YT+ILFCJwKJQ=, FVkevOnZN5di/9MGVnCxW3CwyZsYPwR3arqLx2ni3IU=, fwMcFlh2J4DOspYB0j2jnaotwC1RpVK3IgqP5sOUMzo=, j55/qu5QMgPwmdocyZihSKNhwlhqHdyRRu/3DshxpIM=, O+pcS67/ayurxJ34eqb1nJbj+IQwqlHkl4TH+LqDshg=, UsAGQaVKWqP9Tj/bJc6rOV3smANg1optIjrPBd3hEpc=, NRf9HsGP5asFzqjzyUMiY9aUMxRwhfB6U5YMS4wjuIE=, /CRRWxvsw2s5CtNn772HRTr+BWPfft/NElg8tFlF3YI=, JZbSwGnVzHlbcbLpAqQHBRb6FFshrPPfFdDMdze+aEI=, 7uCPt/dKZOBLvCnbuV6LLyJp7gN6Q3GQDO1K4Kziemg=, /d5kCFEq34TSrjgk3JdqaaySB+7BZLF4N0qVibBYF3g=, Au5Kz6r6YzLHcBUY0UPLjN8jqoPzS/V0s5ILFFAtVo4=, zY1eeUzWBYuPlwJkwF0AEbK+uOM6BZ6j50RnVzgkSgw=, /rCM1rQfJRoxBXu29FBUCLjKaqvFSqezA2rNeRkfCSc=, +u+eo2UEeDlM+qyGjVJDhXp/exscVSxz/FZR4ecixI0=, WyB/715Et/Rfj5ODFAAGoef9xedU8k9NVlwkmrIUEkE=, 6F+rVCWoM6CI6bntw2ZYfEGMTsWrFoX0oVgv3eBY44g=, czIJTTyypb5b63h/2K9FJebPiVS6cCeCtpXpfGzgjig=, kebyTLI2HdgKP8oP53/kxZAFVmDe7KP/YRyWDyAP38g=, DPDgW4INzQIQLOyWexznRjGtBU3Q7kUT0585LF3tED4=, SkBQx1+U5ECBtCFIZ5ijtpy+Xu2sXnpXVKFUfoD2CwU=, ri/yJ8iZpE30PkNyT+x4s48Bbyblv849rufT7x69nVw=, 2wBOLJ4zbLnptTNDCnLPihR+CZi9eGfUtELz5KrgtaU=, GFRYMwFu3TQ0bQvihtNXeMuVJeh6Q6+zY1WroaXBa4k=, 849fL2Qyr/rIllr9bhtCB5IAT5XgoAWRXs1CIGFCiwg=, E4UUxCOvPdVgc8FTcw3n7OWZvuoFvcT3cBSTEgAH5nM=, /AUingOajtr3UxkBGUNpe6kjY3RjNPDzL4D6JSkUkL8=, Bvl4Xxk/Knlp0ZgfsyEPDKadB/8HOe5L1rKEiUra8zw=, XWOjpyqxFTQZ1/nEOToLUrJraAelu7xsqczFmVTh4EU=, U+yePssdT4MftIi58OuuxFUvWcbi92/i80wIABx11dk=, T2gZUoq8vc31q5lJAPhrPJF/Zy1Cp51fVeJv+mms/Cc=, TMCwqunH65+WfquaD5D+D8jqoB+KOUo2qOztYycc+H8=, FAmee3HgN+WpQK77ofb+G24JHWFGDL9NGRwGYCv0H5k=, hzmtav37mdghcmcnx4yzf798tRo6G9nuBei9pLYDoz0=, BF8U01DQLYK5kKMjOVn/XB9J1yf7WxPbe3w7BXCgQwg=, zoVujYxI+B3PugU/wMkG55p//+gJ2UK71H+uPojNe6o=, /DRTgkzjbjJeSQqeV1CmLFCHCzHlzawIWfq+TpolDq0=, ywFo1NkRK2SJ1yt62tMLmnv6bbdkJvvNGMt1WCRMYrk=, 3eL52jo8qYl6CmaI3G43Gx77MUPOjpl6JKHZCs1C9EM=, Of5AxB/RvCZEKoCLDwlmPBi/2TRCCVCj1rsUXI1RIF0=, 6ssMfQkSTOjKzGEyCjeaijHlCmRfqSh2Rl3htGk+slw=, 3NqE7BOYMeI9oAvGX5Yo4JJDz7KuTM3Pz2nsvILMhrE=, 4Sc06MOk4VFbNt1o0uIE1E76+PiKCPmuKIZ72Q8iIOg=, cA6+dBL42u4f9ex72Yf3BuSgiIDr2UazXZPVUM9wg3Y=, e3h2Oxus+NGuqMpiwGuJ4/0tLlCJMc/3inafXq8ZBy0=, vhMlDiqI4W3g9M7rxznNeostGww4g4gHl2t04cUztWI=, uRQ+HCjkDxhZ/Oaz1y20rIX4/CwKsn7fHbNFUiCjc34=, f4YJHg35Z6mRGjBCxns+k7OohYO1IeUK4J29soTfgbQ=, qQt2Tmx+qU3cr/uMEz5c7JMmiVOt1S8Tl7ZKk98UM80=, tYxw3lD++Xqjf8T1SjVOrxZpBfJZ8HR5N9HqoocTGBY=, Cn6ajFfl4hhysy/iocZ5IMee0ULRH026pE3YfPJAFFY=, 5ugViM0hSn2bX+PTxRMUF1Xj7O1blFPSQNoE0y8dRl4=, XViv6dvYUnzus+jiPjuoANgNWVrs/x93h6vEtBkgBzQ=, hpA5yYVV0TZ9L6xbfdEXkMCdVYsgQ/ae9+TEYeS61u8=, 463FKLCdSsQfh2BvhRoRlV+1GH7f83afeq5T0CaRf90=, jtr44NOZS9p7PKYRv93Dtz+E/16dB4P4lYrh4OJuZuY=, 2w8fUmCRUVbbVH/JD3BNU66kEeT93+/k3CdlCuXO8fs=, I/0nkUjDK6TeyoZahPWEMNILwVMgwz2Xm7jR0QX9lnw=, uZxk5kymVDqKYhG9CWuVQ2AAXu7MgwU9MU2zkTM9jwA= from MC after adding Hyi2XVdZ/5D3H/MhwDL/jRWHp3F/dQTmwemyUHW+Urg= with all parents qLVa3jjM5RRAniyO8PgUv9rz+g3z+L12K9f4hUIEG+c=, Hyi2XVdZ/5D3H/MhwDL/jRWHp3F/dQTmwemyUHW+Urg=, yDh2E2F0UODouxS+MBWz/5JAy6tCM37Cpi8mq0Y4NbI=, +ePhyvaKpAl7RHo8EfuUAQLawWrFZuTRchXsmUpvXNM=, PN3NLxUB3bU7n1qwHnlgM823l1pHcwU1Ohjk91Naga0=

**Comment by berbant** [comment]
I have the same thing as author above. 
v 1.11.5

**Comment by raschle** [comment]
+1 same problem as above

**Comment by berbant** [comment]
This issue is gone on 2.0.0. Welcome another one: https://github.com/byteball/byteball/issues/265.

**Comment by Mellorison** [comment]
Has this issue been resolved?

**Comment by tonyofbyteball** [comment]
Yes, install the latest version.
