### ISSUE TITLE
Uncaught exception: Error: message encrypted to unknown key, device ...

### ISSUE THREAD

**Issue by Sorrow2** [byteball/obyte-gui-wallet#250]
Getting error. I think it was in freebe gloabal chat.

> Uncaught exception: Error: message encrypted to unknown key, device 0PUAME4EFN6ROOI5DOMTWPVIRPLKZBLHB, len=228. The error might be caused by restoring from an old backup or using the same keys on another device.

**Comment by shinelikeamillion** [comment]
seam problem

**Comment by tonyofbyteball** [comment]
Click OK and restart https://github.com/byteball/obyte-gui-wallet/issues/283#issuecomment-465640615
