### ISSUE TITLE
After upgrade byteball stops with units.unit=unit_authors.unit)

### ISSUE THREAD

**Issue by pixelchrome** [byteball/obyte-gui-wallet#271]
I've upgraded my byteball installation (macOS). It exits with the message

```
Upgrading the database, please wait. Sometimes it takes several minutes.
units.unit=unit_authors.unit)
```

How to fix this? I already have some bytes in my wallet...

**Comment by pixelchrome** [comment]
With an older version and a backup of the byball folder the error is
```
Uncaught exception: Error: Error: SQLITE_CORRUPT: database disk image is malformed SELECT MAX(lb_units.main_chain_index) AS min_retrievable_mci FROM units JOIN units AS lb_units ON units.last_ball_unit=lb_units.unit WHERE units.is_on_main_chain=1 AND units.is_stable=1
```

**Comment by pixelchrome** [comment]
Looks like this project is dead...

**Comment by SY-MEDIA** [comment]
LOL.... Hardly. https://ostable.org/?r=LTXRMGCRZIQIIMOYFVC4ZGI5AJOSVWXN

**Comment by SY-MEDIA** [comment]
Did you get your wallet issue solved?  If not you can get help in Discord.

**Comment by SY-MEDIA** [comment]
https://discord.obyte.org/

**Comment by SY-MEDIA** [comment]
@pixelchrome LOL.... Hardly. https://ostable.org/?r=LTXRMGCRZIQIIMOYFVC4ZGI5AJOSVWXN
