### ISSUE TITLE
History Labels

### ISSUE THREAD

**Issue by rubbish0815** [byteball/obyte-gui-wallet#281]
Long text labels in gray or blue box are sliced. Better use percentage width combined with ellipsis for a better user experience.

On top the current behavior. On bottom with ellipsis.
![image](https://user-images.githubusercontent.com/18561052/34481148-b81848c6-efb0-11e7-9de3-86b8967fa3ee.png)

**Comment by tonyofbyteball** [comment]
@kakysha

**Comment by tarmo888** [comment]
This should be fixed now? Or still and issue?

**Comment by tonyofbyteball** [comment]
Fixed a few versions ago
