### ISSUE TITLE
Botstore

### ISSUE THREAD

**Issue by rubbish0815** [byteball/obyte-gui-wallet#282]
Adjust boxes for added bots please. Also use ellipsis if text is to long.

![image](https://user-images.githubusercontent.com/18561052/34481237-4a5cc892-efb1-11e7-8bcc-71e0f208b4c7.png)

**Comment by tonyofbyteball** [comment]
@kakysha

**Comment by tarmo888** [comment]
Is this still an issue?

**Comment by tonyofbyteball** [comment]
Alignment fixed a few versions ago.
