### ISSUE TITLE
Improve Wallet Asset Display

### ISSUE THREAD

**Issue by CryptoProsper** [byteball/obyte-gui-wallet#287]
Please consider improving the display of asset names in the wallet. See the screenshot of the wallet home page, attached below.  I am using the MacOS version of the wallet. I am developing stable-value cryptocurrencies on the Byteball platform. Peter Miklos, who is managing the Asset Registry suggested that I make this improvement suggestion here.
a) It would be visually better if the text in the blue box could be centered vertically (moved upwards), or the blue area extended down.
b) A slightly smaller font size for the asset name would improve spacing.
c) Note that the placement of the "D" badge also obscures the text.
Thanks
<img width="371" alt="asset name display" src="https://user-images.githubusercontent.com/35309263/34794396-8098ab30-f61c-11e7-8895-a50f59888ef7.png">

**Comment by tonyofbyteball** [comment]
That's a known problem with long asset names.
We cannot use the second and third lines for the asset name as they are already reserved for other things: pending value, dollar amounts, and shared amount.
It seems the only way to accommodate for long asset names is to display them in radically smaller font size, which I'm going to do in the next release.

**Comment by CryptoProsper** [comment]
Understood.
**a) Font Size:** Assuming that line height is proportional to font size, then reducing the Asset Name font size to one-half of its current size would allow for the display of two lines of text in the same vertical space as the current line height. (Call the new lines "2A" and "2B" for reference here). This would still be very readable: The font size of the menu text at the bottom, "Home", "Receive", "Send", ... is about one-third the font size of the large bold text at the top.
**b) Number of Characters:** The maximum number of "bold" characters that can be displayed per line would go from the current limit of about 16 characters to about 32 characters, allowing more information to display.
**c)Asset Name:** The "shortName", such as "Prosper$ CAD" should appear on line "2A", and the "issuer" should appear on line "2B", such as "by ProsperX.net", keeping the word "by" with the "issuer" on one line, for reasons of clarity.
Thanks.

**Comment by tonyofbyteball** [comment]
Using smaller font size now.
