### ISSUE TITLE
Byteball wallet failed to execute on Ubuntu 16.04

### ISSUE THREAD

**Issue by BoulderPapa** [byteball/obyte-gui-wallet#293]
I downloaded v2.0.1, unzipped the package and execute the program and got the message below.

ken@crypto2:~/Downloads/byteball-linux64$ ./Byteball &
[1] 3450
ken@crypto2:~/Downloads/byteball-linux64$ bash: ./Byteball: cannot execute binary file: Exec format error

I then tried two earlier versions of the wallet and got the same message.

**Comment by BoulderPapa** [comment]
I discovered that my laptop was only a 32 bit machine, which explains why it wouldn't run the wallet.

**Comment by richur** [comment]
are you able to upgrade to 64?
