### ISSUE TITLE
how can run byteball on local linux system

### ISSUE THREAD

**Issue by braravind** [byteball/obyte-gui-wallet#296]
Hello

I download byteball zip from https://github.com/byteball/byteballcore.git and make database connection
on conf.js file.And i use mysql.but after that what i do? How can check byteball run or not.
Please suggest me which command run on next for run byteball?

Thank You

**Comment by stevesbrain** [comment]
Download [this](https://github.com/byteball/byteball/releases/download/v2.1.0/byteball-linux64.zip), extract, and run. Done :)

**Comment by braravind** [comment]
Hello

How can run? which file is run? Because there is not found any index or server.js file.
Please provide me step by step procedure that how can run byteball?
Because i want forking dagcoin and Dagcoin depends on byteball.

Thank You

**Comment by stevesbrain** [comment]
Are you looking to run the byteball client? Or do something else? If you're looking to run the client, there's an executable file in that archive. If not, you may need to build it as per instructions in the README.md file - however, this isn't something I've had to do before.

**Comment by braravind** [comment]
Hello
Yes looking to run the byteball client.And i did not found any arachive fodler or file.I did not understand what you say?
Please provide me helpfull document.

Thank You

**Comment by stevesbrain** [comment]
Assuming you are running this on Linux, then do this:

```bash
wget https://github.com/byteball/byteball/releases/download/v2.1.0/byteball-linux64.zip
unzip byteball-linux64.zip
cd byteball-linux64
./Byteball
```

If you're not running Linux, which system are you running?

**Comment by braravind** [comment]
Hello
I am using linux system.Above process that you mention in your last message.Already i used and open a byteball wallet.Ok But where demon is working ? I want to forking dag coin and generate dagcoin.i want start miner for generate coin.

Thank You

**Comment by stevesbrain** [comment]
@braravind I am not familiar with the daemon sorry - someone else will have to assist with that :)
