### ISSUE TITLE
 Uncaught exception: Error: Error: SQLITE_CORRUPT: database disk image is malformed PRAGMA journal_mode=WAL

### ISSUE THREAD

**Issue by Sircrocus** [byteball/obyte-gui-wallet#314]
My Wallet on opening gives that message.
Couldn't fix it . I have reinstalled wallet different times after erasing the app, Didn't work. 
![image](https://user-images.githubusercontent.com/25556973/39401680-6cf09886-4b21-11e8-9834-361a9eaca52b.png)
Any ideas?
Thank you

**Comment by tonyofbyteball** [comment]
Looks like the database is corrupt and you'll have to revert to a backup.
