### ISSUE TITLE
iOS: wallet unresponsive when coming out of standby

### ISSUE THREAD

**Issue by TheRealCryptKeeper** [byteball/obyte-gui-wallet#339]
Experienced on wallet 2.3.0, installed on an iPhone 7, latest iOS 11.4.

The wallet will be unresponsive if you leave it in a submenu function like ‘settings’ or ‘add contact’ and let the device go into (deep) standby. After coming out of standby, the app just shows the last screen and is frozen. You have to force-shut the app and open it again.

**Comment by tonyofbyteball** [comment]
I don't reproduce exactly this behavior but if I let the phone go to sleep (even when the app is on home tab) and unlock it 10 minutes later, I find the app unloaded from memory.

@kakysha please look into this

**Comment by TheRealCryptKeeper** [comment]
I can’t reproduce this error with the current version 2.4.2 and iOS 11.4.1
