### ISSUE TITLE
2.4.2 not responding, not syncing

### ISSUE THREAD

**Issue by StackmyBCHup** [byteball/obyte-gui-wallet#368]
recently was syncing full wallet as was few weeks behind, 
had to update the mandatory update, which was fine,
then updated to 2.4.2
since then the wallet is not syncing or doing anything
taking a long time for the balance to be displayed
then thats it
clicking anything does nothing

everything has been fine up until this most recent update

Win 10 64 bit

in Task Manager
when wallet is running there are 4 processes
when the wallet is then closed
2 processes continue to run and do not close

**Comment by tonyofbyteball** [comment]
Looks odd, any changes after updating to 2.5.0?

**Comment by StackmyBCHup** [comment]
I reverted back to 2.4.0Then synced againIt got to a certain point and then started to throw an errorThen updated to 2.4.2 againAnd then it began to sync againSent from PORSCHE DESIGN HUAWEI Mate RS-------- Original Message --------Subject: Re: [byteball/byteball] 2.4.2 not responding, not syncing (#368)From: tonyofbyteball To: byteball/byteball CC: StackmyBCHup ,Author Looks odd, any changes after updating to 2.5.0?

**Comment by tonyofbyteball** [comment]
Do you still experience the issue?
