### ISSUE TITLE
Blackbyte textcoins not importing into wallet when clicked on under some conditions

### ISSUE THREAD

**Issue by sientelo** [byteball/obyte-gui-wallet#370]
Blackbyte textcoins were created and saved under this path C:\Users\saargof\Desktop\Ten Blackbyte textcoins of 1000 megabytes

**Ten Blackbyte textcoins of 1000 megabytes** was the folder name.

Clicking on the textcoins when saved in this location produced this error - screenshot https://prnt.sc/kfi11c

When the textcoins were moved from this folder to the desktop the wallet opened the textcoins fine

Believe the issue could be the original folder name had blank spaces

**Comment by tonyofbyteball** [comment]
@kakysha

**Comment by kakysha** [comment]
https://github.com/kakysha/byteball/commit/9b98897d56f9cf99a087d3beadba187b968ca1a0
