### ISSUE TITLE
Byteball wallet cannot open up on windows 10

### ISSUE THREAD

**Issue by abyantony** [byteball/obyte-gui-wallet#401]
1. Downloaded windows 64 bit wallet and installed on windows 10 laptop.
2. And it remains blank and cannot load up.
3. Keep the wallet simple for normal people to use, like iphone.
4. Please refer to attachment 
![byteball wallet cannot load up on new installation](https://user-images.githubusercontent.com/45690754/49651661-c990fd80-fa6a-11e8-80a5-437e9a0fd49f.png)

**Comment by genievot** [comment]
I think you can try to re-install wallet.
If didn't work then follow backup/recovery method, Listed in Byteballcore ReadME On git.

**Comment by abyantony** [comment]
Have tried re-install lot of times. But wallet hangs on the white screen without displaying anything.

**Comment by genievot** [comment]
Go to `appdata` then `Local` and make a backup of folder `Byteball`  and delete it from that location and then start wallet.
It's called backup and recovery.

**Comment by abyantony** [comment]
Thank you. It worked

**Comment by genievot** [comment]
@abyantony  It's ok.  Glad it worked.
