### ISSUE TITLE
Local install of GUI wallet crashed

### ISSUE THREAD

**Issue by creemej** [byteball/obyte-gui-wallet#409]
It always crash with this error:
Jan 20 12:09:43 Jans-MacBook-Pro com.apple.xpc.launchd[1] (com.nw-builder.obyte.4964[2504]): Service exited with abnormal code: 11
This happens when click on "Continue" on page "WELCOME TO BYTEBALL".

IT WORKS FINE WITH NW.js v0.14.7 LTS and Node.js v5.12.0
It doesn't work with the newer versions.

**Comment by tonyofbyteball** [comment]
For newer versions, you have to rebuild binary nodejs modules http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/
