### ISSUE TITLE
Recovery from mnemonic phrase from headless wallet fails

### ISSUE THREAD

**Issue by Crypto2** [byteball/obyte-gui-wallet#410]
I tried to load the mnemonic phrase from my old headless wallet in the GUI wallet but it reports "No active addresses found" and doesn't work.

**Comment by tarmo888** [comment]
Did this resolve your issue? https://github.com/byteball/headless-obyte/issues/36#issuecomment-456489139

**Comment by Crypto2** [comment]
I did switch to light mode but even after 24 hours still showed 0 balance.

**Comment by tonyofbyteball** [comment]
was your headless wallet password protected?

**Comment by Crypto2** [comment]
Yep, it was. I think it was required but it's been years so not 100% sure.

**Comment by tonyofbyteball** [comment]
The GUI wallet can't know the password and therefore can't use this mnemonic.  You can use it only on headless and only with the same password, otherwise the wallet generates different private keys and different addresses.

**Comment by Crypto2** [comment]
I do have the password still and it was the one I used. Weird :(
