### ISSUE TITLE
Using non-sequence unit to attack network without cost

### ISSUE THREAD

**Issue by gaoxiangxyz** [byteball/obyte-gui-wallet#413]
An attacker can send an normal unit and then send many non-sequence units of the normal unit to increase disk usage without any more cost.

**Comment by tonyofbyteball** [comment]
We thought about it when designing the platform, and there are two mitigations:
- honest nodes avoid taking non-serials as direct parents.  Non-serials that stay childless long enough, are removed completely.
- if a non-serial is eventually included, it will be **voided** and most of its payload will be removed.  Only a  part of its size that is critical for DAG integrity stays stored forever.
