### ISSUE TITLE
Renaming of Data Directory for the Rebranding

### ISSUE THREAD

**Issue by D3m0nKingx** [byteball/obyte-gui-wallet#443]
With the new rebranding to Obyte, I noticed that the Data Directory still goes by the old byteball name (**~/.config/byteball**). Will this be changed to **~/.config/Obyte** ? 

If so, what will be the safest way to move my data files over from my current wallet ?

**Comment by tonyofbyteball** [comment]
The data dir was not renamed because it seems impossible to automatically rename it in the existing (upgrading) wallets.  We renamed it in headless wallets, but in GUI wallets, nwjs starts using it before our code executes.
