### ISSUE TITLE
Textcoin share feature not working for Whatsapp

### ISSUE THREAD

**Issue by sientelo** [byteball/obyte-gui-wallet#446]
**Steps**

1. I generate the textcoin string in the Obyte Android wallet 
2. I select the share option -  I see this screen to share the textcoin through an app http://i.imgur.com/8bMwB44.png

**Expected**
Whatsapp app opens so I can paste the message into a chat

**Result**
When I click the name of the whatsapp contact or the whatsapp icon (shown by two red arrows) whatsapp does not open like it should. Instead I am just shown the obyte wallet http://i.imgur.com/ccfopL7.png

This problem exists on both my phones

One is using most recent Android 9.0, the other is Andorid 4.3

**Note**
However I do not have this problem with all apps. For example if I select Google Keep the Google Keeep app opens and I can share the textcoin there http://i.imgur.com/NCmPvbR.png

**Comment by kakysha** [comment]
fixed in v2.7.2
