### ISSUE TITLE
Is there any way to use this React Native ?

### ISSUE THREAD

**Issue by patilrevansidh** [byteball/obyte-gui-wallet#447]
I'm looking for an option to use obyte in react native I don't see this in docs. It seems like for cordova.

**Comment by tarmo888** [comment]
I don't think you can use code that is written for Cordova on React Native. You would need to rewrite this for React Native because this wallet code is Angular + Cordova + NWJS.

So, you can copy-paste some code from this repository, but you have to rewrite it for React Native.
