### ISSUE TITLE
Android wallet Javascript error on switching from WiFi to 4G

### ISSUE THREAD

**Issue by kf106** [byteball/obyte-gui-wallet#458]
**Describe the bug**
On turning off WiFi on Huawei Pro 10 phone Obyte Android SQLite database locked error is raised

**To Reproduce**
1. Start phone connected to WiFi
2. Open Android Obyte wallet (I was using testnet wallet)
3. Turn off WiFi

**Expected behavior**
Wallet to seamlessly switch from WiFi to 4G use

**Screenshots**
![Screenshot_20190703_141838_org byteball wallet testnet](https://user-images.githubusercontent.com/25053735/60587783-fc4f6a00-9d9d-11e9-8672-1f22de2b2e0a.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei Pro 10 COL-L29
 - OS: Android 9.0.0229
 - Browser: Chrome?

**Comment by tarmo888** [comment]
Unable to reproduce it on Android 8.1.0 with Obyte 2.7.2 and Obyte 3.0.1t

Is it still happening or I am missing some step or it's only problem on Android 9? Does it still happen to you with the latest testnet wallet?

**Comment by kf106** [comment]
Unfortunately at the time I reported this I didn't know where to find the Obyte version number. I reproduced it three times back when I reported this. Now I am on 3.0.1t and I am no longer able to reproduce it.
