### ISSUE TITLE
When I tried to run obyte.exe, it crashed.

### ISSUE THREAD

**Issue by NOZHENHAO-123** [byteball/obyte-gui-wallet#459]
When I tried to run obyte.exe, it crashed.
windows

![image](https://user-images.githubusercontent.com/20871325/60659039-0731f980-9e87-11e9-9065-f3601e6aa256.png)

![image](https://user-images.githubusercontent.com/20871325/60658950-d05be380-9e86-11e9-902d-3ef519bd90b2.png)

![image](https://user-images.githubusercontent.com/20871325/60658872-ad313400-9e86-11e9-9188-fbc2780cb00a.png)

**Comment by NOZHENHAO-123** [comment]
Opening screen appears briefly but then closes.

**Comment by tarmo888** [comment]
Did you copied node_modules from project folder to that build folder like it is told in README?
https://github.com/byteball/obyte-gui-wallet#windows
If you did and still crashes then it might be problem with sqlite3 binding libraries, easiest way to get the right ones is to just copy them from the Windows setup.

You actually don't even have to build if you are not trying to develop it, you could just install it with setup and if you are developing it then you could just run nwjs in project folder. If you have run grunt desktop then there is 0.14.7 NW.js already installed in cache folder.
```
cache/0.14.7/win64/nw.exe .
```

**Comment by NOZHENHAO-123** [comment]
thanks for your reply.
I have a new problem. 
I've been depressed for a week trying to solve it.

**Comment by NOZHENHAO-123** [comment]
I tried to compile it into android on Windows.
I follow the steps below:
1: nvm use  8.15.0 (I also tried 'nvm use 4.9.1' )
2: bower install
3: npm install
4: grunt
5: make android-debug
  When I tried to execute the above instructions, an error was reported.
![image](https://user-images.githubusercontent.com/20871325/60779741-6dac6580-a16e-11e9-90ab-d97c58bf2014.png)
  So I go inside the Makefile.
![image](https://user-images.githubusercontent.com/20871325/60779851-d4318380-a16e-11e9-9c87-6ca928a05e78.png)
Each of these three instructions is executed.

**Comment by NOZHENHAO-123** [comment]
finally
I use the android studio，
open ‘obytebuilds\project-ANDROID\platforms\android’.
![image](https://user-images.githubusercontent.com/20871325/60780153-da742f80-a16f-11e9-9f65-8d7c67cf594a.png)

**Comment by sahisandhuu** [comment]
I face same problem on both (windows and android_debug). I try your method but not working. can you tell me how you setup this project in android studio?

**Comment by tonyofbyteball** [comment]
The build instructions have changed significantly since the issue was created. Feel free to reopen if you're still experiencing issues.
