### ISSUE TITLE
Text clipped in Android wallet

### ISSUE THREAD

**Issue by sientelo** [byteball/obyte-gui-wallet#474]
**Steps**

1. Send money to smart contract - in this case I was using the sports betting bot

**Result**

Text is clipped http://i.imgur.com/QZqDEpE.png in smart wallet

**Device**

Android app on 9.0

**Comment by tarmo888** [comment]
That looks like because of the name of the wallet is so long that when smart-contract is selected, it creates a 3rd line, which gets clipped.
