### ISSUE TITLE
Ability to send multiple asset at once from the GUI

### ISSUE THREAD

**Issue by bonustrack** [byteball/obyte-gui-wallet#498]
Is there a plan to add the ability to send a custom amount of byte along with a custom amount of an asset within the GUI? Sending both assets in a single transaction could greatly reduce complexity for some AAs.

**Comment by tonyofbyteball** [comment]
It is possible only by sending a payment request in chat.  The payment request can include payments in multiple assets and user either sends all payments exactly as requested in one transaction or declines the request.  One example is here https://github.com/byteball/obyte-exchange/blob/master/run.js#L206.

Not sure adding a similar functionality on the Send tab would be a good idea, that would make the UI more complex (it already has too many options).

**Comment by bonustrack** [comment]
Ok then maybe it is possible to make chatbot payment request format supported by the protocol URI? So we can trigger user to do a specific operation without the need to run an intermediary chatbot.

**Comment by tonyofbyteball** [comment]
It's one of the possibilities but I'm afraid it won't be easy to add support of such payment requests outside chat.  There are no immediate plans to add this feature, and if we do, it would address only one need.  

Instead, I see a benefit in having a basic chat support in browser. That would enable dapp developers to have two-way communication channel between the browser and the wallet and allow to do the following things without a server: (1) log in to websites, (2) sign messages, (3) share private data, and (4) pay specially crafted payment requests such as you need.

**Comment by bonustrack** [comment]
I see yes, make sense to have such chatbot thank you.
