### ISSUE TITLE
Getting "JavaScript error: Uncaught " message after restoring a backed up wallet

### ISSUE THREAD

**Issue by neupanedipen** [byteball/obyte-gui-wallet#502]
I had taken a back up of my wallet about a year ago. Now when I tried to open the wallet on my phone after restoring the backup, I am constantly getting "JavaScript error: Uncaught SyntaxError: Unexpected end of input" message.
The back up was taken in a different device.
Here's a screenshot of the error I am getting :
https://i.postimg.cc/V6xMqT7L/Screenshot-2020-02-15-12-35-23.png

**Comment by tarmo888** [comment]
This should be fixed on latest version.
