### ISSUE TITLE
Cannot read property 'replace' of undefined; cause: undefined

### ISSUE THREAD

**Issue by pmiklos** [byteball/obyte-gui-wallet#504]
**Describe the bug**
When opening a smart contract definition in the wallet I get the following error and then the wallet crashes. I can't exactly see the contract conditions because the error dialog hides it but I think this is a contract of the real name attestation reimbursement. The error message is

  An exception occurred: TypeError: Cannot read property 'replace' of undefined; cause: undefined

**To Reproduce**
It may be specific to this contract I have, it's a year old some bytes are still stuck in there, . See address [MZ4PLO7GUE47ZOMBR5CAEW3GAKV4IWRB](https://explorer.obyte.org/#MZ4PLO7GUE47ZOMBR5CAEW3GAKV4IWRB)

**Expected behavior**
The contract definition shown, wallet shouldn't crash.

**Screenshots**
![Screenshot from 2020-02-26 22-27-53](https://user-images.githubusercontent.com/2352609/75418100-757c6e00-58e7-11ea-8774-bf28f1c0dc3f.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - GUI Wallet Version: 3.0.1

**Comment by tarmo888** [comment]
This is fixed in 3.0.2
