### ISSUE TITLE
How can I get the initial coins of the testnet?

### ISSUE THREAD

**Issue by twepl** [byteball/obyte-gui-wallet#507]
I need to run a test and get initial coins of 1 000 000 how can I do this?

**Comment by tarmo888** [comment]
testnet wallet should have faucet chat bot on Chat screen. there is link to that chat bot also on the page where you can download the testnet wallet
https://obyte.org/testnet.html

**Comment by twepl** [comment]
Не против если я по русски буду писать, я бы хотел не просто получит монеты тестнет а создать новый узел с 0 блоком и получить начальные монеты разработчика.
Я же правильно понимаю, что ваша криптовалюта без майнинга и все монеты доступны в самом начале.
А дальше я попробую передать эти монеты в локальной сети между компьютерами.
