### ISSUE TITLE
Error when trying to run the Appimage on Linux

### ISSUE THREAD

**Issue by CannonVegetable** [byteball/obyte-gui-wallet#513]
**Describe the bug**
Trying to run the wallet from the new Appimage doesn't work.

**To Reproduce**
1. Double-click obyte-x86_64.appimage
2. Nothing happens / doesn't start

OR
1. Open terminal and navigate to the appimage directory
2. type `./obyte-x86_64.appimage`
3. Application doesn't start and you get this error:
`Obyte: /tmp/.mount_obyte-zyONWh/usr/lib/x86_64-linux-gnu/libgnutls.so.30: version 'GNUTLS_3_6_3' not found (required by /lib/x86_64-linux-gnu/libcups.so.2)`

**Expected behavior**
The application should start

**Desktop:**
 - OS: Kubuntu 19.10 64bit
 - Kernel version: 5.3.0-46-generic
 - OS Libraries
     - libgnutls30: 3.6.9-5ubuntu1.1
     - libcups2: 2.2.12-2ubuntu1

**Additional context**
I of course made the file executable.
I can run the 3.0.2 release

**Comment by Papabyte** [comment]
Thanks for your report. We will release a new appimage soon to fix this issue.

**Comment by tarmo888** [comment]
This should be fixed in 3.1.0

**Comment by CannonVegetable** [comment]
I tried it just now and it's working. Thanks.
