### ISSUE TITLE
Obyte wallet not opening on mac . please help

### ISSUE THREAD

**Issue by volkanyenel** [byteball/obyte-gui-wallet#520]
i am trying to poen my wallet however i doesnt opening / please help how to recover it

**Comment by relay10panelF** [comment]
same here. obyte app is crashing shortly after launch. (on macbook pro; osx el capitan 10.11.6)
mac osx console is telling me:

04.08.20 09:58:43,000 kernel[0]: nwjs[944] triggered unnest of range 0x7fff8a400000->0x7fff8a600000 of DYLD shared region in VM map 0x7290e94314b66f5f. While not abnormal for debuggers, this increases system memory footprint until the target exits.

04.08.20 09:58:43,000 kernel[0]: nwjs Helper[948] triggered unnest of range 0x7fff8a400000->0x7fff8a600000 of DYLD shared region in VM map 0x7290e94316a56b07. While not abnormal for debuggers, this increases system memory footprint until the target exits.

04.08.20 09:58:43,401 nwjs[944]: NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.

04.08.20 09:58:43,000 kernel[0]: nwjs Helper[949] triggered unnest of range 0x7fff8a400000->0x7fff8a600000 of DYLD shared region in VM map 0x7290e94316a58057. While not abnormal for debuggers, this increases system memory footprint until the target exits.

04.08.20 09:58:43,685 launchservicesd[83]: SecTaskLoadEntitlements failed error=22
04.08.20 09:58:43,691 launchservicesd[83]: SecTaskLoadEntitlements failed error=22
04.08.20 09:58:45,493 com.apple.xpc.launchd[1]: (com.nw-builder.obyte.104352[944]) Service exited with abnormal code: 4

**Comment by sunk818** [comment]
I'm having same issue on 10.13.6  - I tried clearing all the app data, uninstall OByte from Applications. Reinstall. The folder I deleted is byteball, not obyte folder. I agree to the terms, then select the default lite wallet option. When I continue, the app crashes.

**Comment by relay10panelF** [comment]
fixed in the new version
