### ISSUE TITLE
Could not compile the wallet application, please help

### ISSUE THREAD

**Issue by MarkTangJs** [byteball/obyte-gui-wallet#574]
**Describe the bug**
I installed the environment according to the document, 
run `make android-debug`, An error occurred: 
`This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry`

run `make ios-debug`, An error occurred:
`project-IOS-tn/platforms/ios/Obyte/CDVLaunchScreen.storyboard:Ze5-6b-2t3: error: Named colors do not work prior to iOS 11.0. [12]`

**To Reproduce**
for Android:
1. `git clone https://github.com/byteball/obyte-gui-wallet.git &&
cd obyte-gui-wallet`
2. `npm install -g bower`
3. `npm install -g grunt-cli`
4. `bower install`
5. `env CXXFLAGS="-mmacosx-version-min=10.9" LDFLAGS="-mmacosx-version-min=10.9"`
6. `npm install`
7. `grunt`
8. `grunt desktop`
9. `npm install cordova -g`
10. `brew install gradle`
11. `make android-debug`

for IOS:
1. `git clone https://github.com/byteball/obyte-gui-wallet.git &&
cd obyte-gui-wallet`
2. `npm install -g bower`
3. `npm install -g grunt-cli`
4. `bower install`
5. `env CXXFLAGS="-mmacosx-version-min=10.9" LDFLAGS="-mmacosx-version-min=10.9"`
6. `npm install`
7. `grunt`
8. `grunt desktop`
9. `npm install cordova -g`
10. `npm install -g ios-deploy`
11. `brew install cocoapods`
12. `pod setup`
13. `make ios-debug`

**Expected behavior**
Android IOS normal operation.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10

**Smartphone (please complete the following information):**
 - Device: Iphone 11
 - OS: IOS 13.7

**Additional context**
Other configuration:
Node.js Version: 10.16.0
Npm Version: 6.9.0
AndroidStudio Version: 4.0.1
Xcode: 12.0
Cordova Version: 10.0.0

Is it a Cordova version issue? Cause the packaged code is wrong?

**Comment by kakysha** [comment]
I have cordova v 9.0.0, which on `make android-debug` installs cordova-android@8.1.0.
Can you check if cordova v9 works for you? just `npm install -g cordova@9.0.0`

**Comment by MarkTangJs** [comment]
> I have cordova v 9.0.0, which on `make android-debug` installs cordova-android@8.1.0.
> Can you check if cordova v9 works for you? just `npm install -g cordova@9.0.0`

Still can't run.   What is your node version?   I suspect it is a npm version problem.

**Comment by kakysha** [comment]
❯❯❯ node -v
v8.11.3
 ❯❯❯ npm -v
5.6.0

**Comment by xJeneKx** [comment]
> > I have cordova v 9.0.0, which on `make android-debug` installs cordova-android@8.1.0.
> > Can you check if cordova v9 works for you? just `npm install -g cordova@9.0.0`
> 
> Still can't run. What is your node version? I suspect it is a npm version problem.

Hey! I made fixes, there should be no problems with the build now. Try it now.
