### ISSUE TITLE
Uncaught exception: Error: unit not found: 

### ISSUE THREAD

**Issue by Trotadorcillo** [byteball/obyte-gui-wallet#593]
Since yesterday, when opening the wallet I get this error message

"Uncaught exception: Error: unit not found: G4uP1MIBAPmE2ZzwavEdUJZnvFi2EzLcnIrTvwjfTO0="

I can only select "OK" and the wallet closes itself. I can see behinf the error message widow that the wallet has initiated and my name appears.

Ubuntu 18.04 system, I had a power cut at home yesterday, don't know whether it relates to it but did not occur before.

Thanks

**Comment by tarmo888** [comment]
Looks like your wallet got corrupted during the power cut, which can happen if wallet writes data at the same time as the power cut. More likely happens with full nodes than light nodes.

If you are running a full node and doesn't care about any private data in your wallet (private assets like blackbytes, smart-contracts, multi-sig accounts, chat logs), then probably easiest to recover is to delete sqlite files and rocksdb folder and re-sync the wallet again.

If you are running a light node and you have recent encrypted backup (restores private data from backup date) or seed words (doesn't restore private data), then you could restore the wallet from them.

**Comment by Trotadorcillo** [comment]
Thanks for the answer, I have a light wallet and a couple of encrypted backups. Since the wallet does not open, how should I proceed?, rename/delete byteball folder in .config and install/restore?, thanks for your help, newbie here.

**Comment by tarmo888** [comment]
Yeah, you can rename the folder in .config and next time you start the app, it will create a new blank wallet and you can then restore the backup. You should restore the latest encrypted backup.

If you are restoring some very old backup then balances on accounts with multiple addresses might be out of sync, but the funds are actually there and will appear once you have use the account (sometimes helps to press the "Generate new address" button.

**Comment by Trotadorcillo** [comment]
Ok, it seems going well, restored a backup from 20th October and now it is syncing. The figure looks ok to me :).

Thanks!

**Comment by Trotadorcillo** [comment]
Syncing completed, back to previous status.
