### ISSUE TITLE
 Uncaught exception: Error: checkBalances failed

### ISSUE THREAD

**Issue by Trotadorcillo** [byteball/obyte-gui-wallet#602]
Hi again,
Unfortunately another error when starting the wallet. This time no power cut occurred:
==============0
 Uncaught exception: Error: checkBalances failed: sql: SELECT aa_balances.address, aa_balances.asset, balance, SUM(amount) AS calculated_balance FROM aa_balances LEFT JOIN outputs INDEXED BY outputsByAddressSpent ON aa_balances.address=outputs.address AND is_spent=0 AND outputs.asset=aa_balances.asset AND ( (SELECT is_stable FROM units WHERE units.unit=outputs.unit)=1 OR EXISTS (SELECT 1 FROM unit_authors CROSS JOIN aa_addresses USING(address) WHERE unit_authors.unit=outputs.unit) ) WHERE aa_balances.asset!='base' GROUP BY aa_balances.address, aa_balances.asset HAVING balance != calculated_balance rows:[ { "address": "KBNDYMU...
===========0
Some addresses appear after That I've peferred not to copy here.
Thanks and regards

**Comment by Trotadorcillo** [comment]
Sorry forgot to say that wallet opens but less than a second after appears this exception window that closes the wallet after clicking 
regards

**Comment by tarmo888** [comment]
yes, this bug happened today and affected most full nodes, you can either wait for new GUI wallet release or apply this patch to node_modules/ocore/aa_composer.js

https://github.com/byteball/ocore/commit/9512dd8cbdf3a644f8bc7f2dc3850f293710fb6c

**Comment by Trotadorcillo** [comment]
Thanks, I will wait for the new version of the wallet.

**Comment by motqalden** [comment]
Hi I am also having this issue and have a couple of questions:
1. Do we still continue to get proof of work rewards even if the wallet isn't running?  (in case i decide to wait for new release.
2. Do you have any instructions on how to apply the patch?  I tried editing the file directly and replacing it but it says i don't have permission to do so.

**Comment by tarmo888** [comment]
@motqalden what Proof of Work rewards? Obyte os not Proof of Work.

If you think World Community Grid distribution then that has nothing to do with Obyte wallet, you do that work with BOINC and you just get airdropped bytes and WCG points to your address.

You need to have admin privileges to edit program files, better wait for next release if that's too complicated.

**Comment by motqalden** [comment]
Interesting I thought the WCG distribution was part and parcel of the Obyte and calling it "proof of work"  was sort of a non official title to describe the function so to speak.

I didn't realize it was simply me not editing it with admin access.
I managed to edit in and add the additional lines to ignore the discrepancy and my wallet is syncing again so thank you for your reply :)

**Comment by tarmo888** [comment]
@Trotadorcillo @motqalden there is a new wallet version available now.
https://github.com/byteball/obyte-gui-wallet/releases
