### ISSUE TITLE
 Uncaught exception: TypeError: Cannot set property 'sequence' of undefined

### ISSUE THREAD

**Issue by Trotadorcillo** [byteball/obyte-gui-wallet#637]
Hi.
I get this error when opening the wallet. Two days ago I did some transfer which went OK and the wallet closed well. No issue with the PC either.

Thanks for advising on how to proceed.

**Comment by tarmo888** [comment]
if you have full node GUI wallet, you either have to wait for next app release or manually update these files in `C:\Program Files\Obyte\node_modules\ocore` folder
https://raw.githubusercontent.com/byteball/ocore/master/parent_composer.js
https://raw.githubusercontent.com/byteball/ocore/master/main_chain.js

**Comment by Trotadorcillo** [comment]
> if you have full node GUI wallet, you either have to wait for next app release or manually update these files in `C:\Program Files\Obyte\node_modules\ocore` folder
> https://raw.githubusercontent.com/byteball/ocore/master/parent_composer.js
> https://raw.githubusercontent.com/byteball/ocore/master/main_chain.js

Sorry, I'm using ubuntu

**Comment by Trotadorcillo** [comment]
It looks like 3.4.0. is out. Should I install it directly or i have first  to rename the ./config/byteball folder?
Thanks

**Comment by tarmo888** [comment]
@Trotadorcillo no renaming, the data folder path never changed and is same for all versions.

**Comment by Trotadorcillo** [comment]
Ok, thanks!, installed and working
