### ISSUE TITLE
Could not send payment: unable to find parents

### ISSUE THREAD

**Issue by clayt0nk** [byteball/obyte-gui-wallet#655]
I have a very old single-device wallet, the last transaction was years ago. I am now trying to send the "bytes" balance to a newly-minted multi-sig multi-device wallet, and the transaction repeatedly fails with the message

`Could not send payment: unable to find parents: failed to find parents: witness level would retreat from 5431577 to 5431571`

Sending device is a Desktop (please complete the following information):
 - OS: Debian 12
 - Desktop Obyte wallet v4.0.0

**Additional context**
Not the best network connectivity where I live, this happens with and without VPN

**Comment by tonyofbyteball** [comment]
Since you say your wallet is old, most likely your order provider list is outdated. Please open the burger menu, Settings, Order Providers, and enable the Auto-update, then try again. Please report here if it helped.

**Comment by clayt0nk** [comment]
Yes, that was the trick, thanks! Everything works now. Note to future wallet drainers: FIRST drain your blackbytes, THEN drain your bytes. The reverse order does not seem to work, as blackbytes insist on paying their transaction fees with bytes.

**Comment by tonyofbyteball** [comment]
Of course, fees are always paid with bytes.
